services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    command: yarn start
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/usr/src/app
    ports:
      - '3000:3000'
